alias gd="git diff"
alias gl="git log"
alias gs="git status"
alias ga="git add"
alias gc="git commit"
alias gp="git push"
alias gm="git merge"
alias gpl="git pull"
alias gb="git branch"
alias go="git checkout"
alias gco="git checkout"
alias gpu="git rev-parse --abbrev-ref HEAD | xargs git push -u origin" # push new branch to origin
alias gpuf='git push --force-with-lease origin "$(git name-rev --name-only HEAD)"' # safely force-push the current branch
alias addtocommit="git commit . --amend --no-edit"
alias gitreset="git reset --hard HEAD"
alias delete_merged_branches='git branch --merged | egrep -v "(^\*|master|dev)" | xargs git branch -d' # https://stackoverflow.com/a/6127884/5841356
