alias gd="git diff"
alias gs="git status"
alias ga="git add"
alias gc="git commit"
alias gpl="git pull"
alias gb="git branch"
alias gco="git checkout"
alias grbc="git rebase --continue"
alias gp="git push"
alias gpu='git push -u origin "$(git name-rev --name-only HEAD)"' # push new branch to origin
alias gpuf='git push --force-with-lease origin "$(git name-rev --name-only HEAD)"' # safely force-push the current branch
alias addtocommit="git commit . --amend --no-edit"
alias gitreset="git reset --hard HEAD"
alias delete_merged_branches='git branch --merged | egrep -v "(^\*|master|dev|main)" | xargs git branch -d' # https://stackoverflow.com/a/6127884/5841356
